### ISSUE TITLE
Add custom background support

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/RiiTag-Next#12]
I believe some people would like to have their own custom RiiTag background. An upload form could be made to send backgrounds in 1200x450 size in an approval queue that admins can check.

If this is done, it would be nice to support Pushover notifications for it. Pushover's an app I have on my phone. When someone uploads a custom background, I could get a notification with Pushover.

**Comment by Brawl345** [comment]
Very low priority. Tbh we currently have too much backgrounds and personally I would delete every one of them that is used less than 15-20 times. The background selection is huge currently and includes some... odd choices. Opening the modal is very taxxing on the browser (could split into pages but would need extra effort + and a search function). No one should have their "own individual background".

**Comment by Brawl345** [comment]
Unless you mean a "private banner" that is not shown in the list for everyone, but each user can upload it for themselves (like profile banners on Twitter or Facebook). I haven't thought about this.

**Comment by Furdox** [comment]
Personnally, I think the only public backgrounds would be "generic" backgrounds like the Wii menu and that users would be able to upload their own banner privately (probably using some sort of template or resize tool). Also, you could privately upload your custom coin, flag and ttf font.

**Comment by GreenDiscord** [comment]
Was wondering, how would people think about a way for site admins to categorise backgrounds? Currently as @Brawl345 say, there are quite a lot of backgrounds and this could make it a bit less cluttered. Any ideas to update the background system I'm fully open too.

**Comment by larsenv** [comment]
Added in https://github.com/RiiConnect24/RiiTag-Next/commit/96e304be6857653e9489d5fcc0df6f9acb7ac34e.
